name: Docker Actions

on: workflow_dispatch

#on:
#  pull_request:
#    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: netcore-action
        uses: ./.github/actions/netcore-action
